name: Update
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '18 0 * * *'

jobs:
  build:
    name: Update Job
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup gh-pages output folder
        shell: bash
        run: |
          git clone --single-branch -b gh-pages "$(git remote get-url origin)" out
          git -C out config credential.helper "$(git config credential.helper)"
          git -C out config 'http.https://github.com/.extraheader' "$(git config 'http.https://github.com/.extraheader')"
          git -C out config core.autocrlf input
          git -C out rm -rf --ignore-unmatch .
          git -C out clean -fxd
          cp README.md out/
          cp -r swagger-ui/dist out/tool
          git apply index.html.diff

      - name: Install & Update League of Legends
        run: |
          choco install -y leagueoflegends
          & 'C:\Riot Games\League of Legends\LeagueClient.exe'
          Start-Sleep 180

      - name: Run update.ps1
        env:
          LOLLOGIN: ${{ secrets.lollogin }}
        run: |
          $env:LOLLOGIN | Out-File -Encoding UTF8 'lollogin.json'
          .\update.ps1
        shell: powershell # Use powershell 5 (not 7)

      - name: Push changes in output folder
        shell: bash
        run: |
          git -C out add .
          changes=$(git -C out diff --cached -U0 | grep '^[+-][^+-]' |
              grep -v 'Http' | grep -v 'LOCKED"' |
              grep -v '"requirement_owned"' | wc -l)
          echo "Changes: $changes"
          if [ $changes -gt 5 ]; then
            git -C out -c user.name='github-actions[bot]' -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \
                commit -m "Update $(date -u -Is), script $(git log --pretty=format:%h -n 1)"
            git -C out push
          fi
